### ISSUE TITLE
Function return reference give error

### ISSUE THREAD

**Issue by crbast** [zircote/swagger-php#1271]
*zircote/swagger-php version : 4.2.11*

When a function with a reference as output is present in a file, we receive :
```
Warning: Uninitialized string offset 1
```

My code : 
```php
<?php
...
    public function &all(): array
    {
        return $this->texts;
    }
...

```

When I remove the `&`, the docs work.

Full error message : 
```json
{
   "code":0,"message":"Warning: Uninitialized string offset 1",
   "stack":"#0 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Analysers\/TokenScanner.php(21): OpenApi\\Analysers\\TokenScanner-\u003EscanTokens(Array)\n#1 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Analysers\/ReflectionAnalyser.php(49): OpenApi\\Analysers\\TokenScanner-\u003EscanFile(\u0027\/var\/www\/html\/s...\u0027)\n#2 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Generator.php(378): OpenApi\\Analysers\\ReflectionAnalyser-\u003EfromFile(\u0027\/var\/www\/html\/s...\u0027, Object(OpenApi\\Context))\n#3 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Generator.php(376): OpenApi\\Generator-\u003EscanSources(Object(Symfony\\Component\\Finder\\Finder), Object(OpenApi\\Analysis), Object(OpenApi\\Context))\n#4 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Generator.php(342): OpenApi\\Generator-\u003EscanSources(Array, Object(OpenApi\\Analysis), Object(OpenApi\\Context))\n#5 \/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Generator.php(294): OpenApi\\Generator-\u003Egenerate(Array, Object(OpenApi\\Analysis), true)\n#6 \/var\/www\/html\/src\/Controller\/ApiController.php(189): OpenApi\\Generator::scan(Array)\n#7 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(152): App\\Controller\\Controller-\u003EgetSwagger()\n#8 \/var\/www\/html\/vendor\/symfony\/http-kernel\/HttpKernel.php(74): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#9 \/var\/www\/html\/vendor\/symfony\/http-kernel\/Kernel.php(202): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#10 \/var\/www\/html\/vendor\/symfony\/runtime\/Runner\/Symfony\/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel-\u003Ehandle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#11 \/var\/www\/html\/vendor\/autoload_runtime.php(35): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner-\u003Erun()\n#12 \/var\/www\/html\/public\/index.php(5): require_once(\u0027\/var\/www\/html\/v...\u0027)\n#13 {main}"
}
```

Thank you for your help :)

**Comment by DerManoMann** [comment]
Hi @crbast could you try the PR branch #1274 to see if that fixes your issue?

**Comment by crbast** [comment]
Hello @DerManoMann , sorry for the late answer. Yes it's working fine. 

Thank you a lot for your work :)
