### ISSUE TITLE
Attributes: Reference other schema in an array property

### ISSUE THREAD

**Issue by jbreu** [zircote/swagger-php#1440]
First, let me thank you very much for this very cool project. I have been using swagger-php for some years now in my pet project. Recently I started to migrate to attributes, but I get stuck with the below problem. I already checked the examples and dozens of issues, but couldnt find anything directly related.

I have this schema (simplified):
```
#[OA\Schema(schema: 'Assignment')]
class Assignment {
...
```

In another schema I want to reference it in an array property. With annotations it was working via

```
  /**
   * @OA\Property(
   *    type="array",
   *    @OA\Items(ref="#/components/schemas/Assignment")
   * )
   */
```

However, with attributes I dont really get it working:

```
 #[OA\Property(
    type: 'array',
    items: #[OA\Items(type: Assignment::class)]
  )]

```

**Comment by DerManoMann** [comment]
Almost there.

PHP attributes do not really have syntax for nesting - its just regular PHP code, so this should work:
```php
#[OA\Property(
    type: 'array',
    items: [new OA\Items(type: Assignment::class)]
  )]
```

**Comment by jbreu** [comment]
Thanks @DerManoMann , however it doesnt work like this, see below. Thats why I thought "Items" is already an array-like thing because of the plural naming...

```
Debug: Analysing source: src\Model\Task.php
Debug: Could not instantiate attribute: OpenApi\Attributes\Property::__construct(): Argument #12 ($items) must be of type ?OpenApi\Attributes\Items, array given, called in C:\Users\Jakob\Documents\workspace\taskr_backend\src\Model\Task.php on line 34
#0 C:\Users\Jakob\Documents\workspace\taskr_backend\src\Model\Task.php(34): OpenApi\Attributes\Property->__construct(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'array', NULL, Array)
#1 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\src\Analysers\AttributeAnnotationFactory.php(42): ReflectionAttribute->newInstance()
#2 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(159): OpenApi\Analysers\AttributeAnnotationFactory->build(Object(ReflectionProperty), Object(OpenApi\Context))
#3 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\src\Analysers\ReflectionAnalyser.php(57): OpenApi\Analysers\ReflectionAnalyser->analyzeFqdn('Src\\Model\\Task', Object(OpenApi\Analysis), Array)
#4 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\src\Generator.php(493): OpenApi\Analysers\ReflectionAnalyser->fromFile('src\\Model\\Task....', Object(OpenApi\Context))
#5 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\src\Generator.php(455): OpenApi\Generator->scanSources(Object(Symfony\Component\Finder\Finder), Object(OpenApi\Analysis), Object(OpenApi\Context))
#6 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\zircote\swagger-php\bin\openapi(233): OpenApi\Generator->generate(Object(Symfony\Component\Finder\Finder))
#7 C:\Users\Jakob\Documents\workspace\taskr_backend\vendor\bin\openapi(120): include('C:\\Users\\Jakob\\...')
#8 {main}
```

**Comment by DerManoMann** [comment]
Ah, of course. The [] were still leftover from the wrong #[] syntax; the error message actually says it.

**Comment by jbreu** [comment]
Ah now I got it :-)
Thanks

```
  #[OA\Property(
    type: 'array',
    items: new OA\Items(type: Assignment::class)
  )]
```
