### ISSUE TITLE
Generating doesnt work without description

### ISSUE THREAD

**Issue by shapito27** [zircote/swagger-php#667]
I'm new swagger-php user.
Trying to generate from:
```
<?php
/**
 * @OA\Info(title="My First API", version="0.1")
 */

/**
 * @OA\Get(
 *     path="/api/resource.json",
 *     @OA\Response(response="200", description="An example resource")
 * )
 */
```
using this code:
```
<?php
require("vendor/autoload.php");
$openapi = \OpenApi\scan('/path/to/project');
header('Content-Type: application/x-yaml');
echo $openapi->toYaml();
```
but getting error:
```
Fatal error: Uncaught TypeError: trim() expects parameter 1 to be string, boolean given in /home/bitrix/www/vendor/zircote/swagger-php/src/Context.php:213 
Stack trace: 
#0 /home/bitrix/www/vendor/zircote/swagger-php/src/Context.php(213): trim(false) 
#1 /home/bitrix/www/vendor/zircote/swagger-php/src/Processors/AugmentOperations.php(27): OpenApi\Context->phpdocDescription() 
#2 /home/bitrix/www/vendor/zircote/swagger-php/src/Analysis.php(361): OpenApi\Processors\AugmentOperations->__invoke(Object(OpenApi\Analysis)) 
#3 /home/bitrix/www/vendor/zircote/swagger-php/src/functions.php(44): OpenApi\Analysis->process(Array) 
#4 /home/bitrix/www/swagger/index.php(7): OpenApi\scan('/home/bitrix/ww...') 
#5 {main} thrown in /home/bitrix/www/vendor/zircote/swagger-php/src/Context.php on line 213
```

But when i added description for @OA\Get
```
/**
 * @OA\Get(
 *     path="/api/resource.json",
 *     description="An example",
 *     @OA\Response(response="200", description="An example resource")
 * )
 */
```
It works.
Now description is required?

What is the problem?

**Comment by bfanger** [comment]
With *or* without description I don't get *any* errors.

Skimming through the code I only see functions that return strings. 
Something went wrong and returned a `false`.
Could you find out what went wrong and  causes the `false` that is passed to `trim()`?

**Comment by bfanger** [comment]
Seems `mbstring.func_overload` could have been the issue. https://github.com/zircote/swagger-php/issues/665
