### ISSUE TITLE
Why class 'OpenApi\Processors\Generator' not found?

### ISSUE THREAD

**Issue by KartoshkaPy** [zircote/swagger-php#961]
Hi! I installed swagger-php and getting this error.

Full error message:
```
[Mon Jun 28 11:58:55 2021] [::1]:48800 [500]: / - Uncaught Error: Class 'OpenApi\Processors\Generator' not found in /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/vendor/zircote/swagger-php/src/Processors/MergeIntoOpenApi.php:38
Stack trace:
#0 /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/vendor/zircote/swagger-php/src/Analysis.php(435): OpenApi\Processors\MergeIntoOpenApi->__invoke(Object(OpenApi\Analysis))
#1 /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/vendor/zircote/swagger-php/src/Generator.php(234): OpenApi\Analysis->process(Array)
#2 /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/vendor/zircote/swagger-php/src/Generator.php(211): OpenApi\Generator->generate(Array, Object(OpenApi\Analysis), true)
#3 /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/Swagger/Generator.php(18): OpenApi\Generator::scan(Array)
#4 /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/index.php(11): Swagg in /home/kartoshka/Документы/projects/GO/my/web/qbasket/services/cloud/vendor/zircote/swagger-php/src/Processors/MergeIntoOpenApi.php on line 38
```
I checked library source code and noticed that Generator.php is in src.

MergeIntoOpenApi.php is in Processors.
 
This is MergeIntoOpenApi.php source code:

![image](https://user-images.githubusercontent.com/59607313/123602431-c832a680-d809-11eb-8954-2521b5a9c5c2.png)

I add `use OpenApi\Generator;` and that works!

Then library source code look like:

![image](https://user-images.githubusercontent.com/59607313/123602726-1ba4f480-d80a-11eb-90bb-f685b7b2b0a3.png)

Is this a bug?
Why Generator don't used? 

I noticed a problem in my repo: https://github.com/qBasket-File-Sharing-Platform/Cloud-Service

What do i did?
```php
namespace Swagger;

use OpenApi\Generator as OpenApiGenerator;

class Generator {
    private $pathToProject;
    private $pathToGeneratedJsonFile;

    public function __construct($pathToProject, $pathToGeneratedJsonFile)
    {
        $this->pathToProject = $pathToProject;
        $this->pathToGeneratedJsonFile = $pathToGeneratedJsonFile;
    }

    public function generate()
    {
        $openapi = OpenApiGenerator::scan([$this->pathToProject]);

        $fp = fopen($this->pathToGeneratedJsonFile, "wb");
        fwrite($fp, $openapi->toJson());
        fclose($fp);
    }
}
```
```php
generator = new Generator(".", "Swagger/swagger.json");
$generator->generate();
```

How did I install this?
`composer require zircote/swagger-php`

My composer.json
```json
"require": {
    "ext-json": "*",
    "zircote/swagger-php": "^3.2"
}
```

What do i did wrong or it's a bug?

**Comment by DerManoMann** [comment]
Thanks for the details report. This is, in fact, a bug. 
It had been fixed a few days ago and I just created a new release, so updating your swagger-php deps should fix the issue.
